/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expresso_report_package;

/**
 *
 * @author JM Marquez
 */

import com.sun.media.sound.InvalidFormatException;
import java.awt.Cursor;
import java.io.*;
import java.util.*;
import java.util.Calendar;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.poi.EncryptedDocumentException;
import org.apache.poi.POIXMLException;
import org.apache.poi.openxml4j.opc.OPCPackage;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellValue;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.FormulaEvaluator;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFFormulaEvaluator;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class FSComparativeConsoJInternalFrame extends javax.swing.JInternalFrame {
    private static final SimpleDateFormat SDF = new SimpleDateFormat( "yyyy-MM-dd" );
    /**
     * Creates new form FSComparativeConsoJInternalFrame
     */
    public FSComparativeConsoJInternalFrame(String repcode) throws SQLException, IOException {
        initComponents();
        //this is the old code
        Connection conn = ConnectionManager.getConnection();
        Statement st = conn.createStatement();      
        String sql;

        sql = "select name from branch order by id;";
        ResultSet rs = st.executeQuery(sql);
        rs = st.executeQuery(sql);
        while (rs.next())
        {

        }

        rs.close();
    }
    FSComparativeConsoJInternalFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalReportCutOff = new org.freixas.jcalendar.JCalendarCombo();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        J = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("ERP-FS");
        getContentPane().setLayout(null);

        jCalReportCutOff.setName("fsDateString"); // NOI18N
        jCalReportCutOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalReportCutOffActionPerformed(evt);
            }
        });
        getContentPane().add(jCalReportCutOff);
        jCalReportCutOff.setBounds(170, 50, 240, 50);

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel1.setText("Report Cut-Off Date:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 140, 50);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(170, 150, 90, 40);

        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerate);
        btnGenerate.setBounds(260, 150, 150, 40);

        J.setMaximum(23);
        J.setStringPainted(true);
        getContentPane().add(J);
        J.setBounds(170, 110, 240, 20);

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel2.setText("COMPARATIVE CONSOLIDATED FS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 0, 380, 40);

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel3.setText("Progress");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 70, 30);

        setBounds(0, 0, 431, 274);
    }// </editor-fold>//GEN-END:initComponents

    private void jCalReportCutOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalReportCutOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCalReportCutOffActionPerformed
    int selectedIndex,count=0;
    String selectedBranch;
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //reportparameterframe.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed

        System.out.println("======================= GENERATE FINANCIAL STATEMENT ==========================");

        System.out.println("START");
        Thread thread;
        thread = new Thread(new Runnable(){
            @Override
            public void run(){
                String dateString = SDF.format( jCalReportCutOff.getDate() );
                Calendar cal = Calendar.getInstance();
                String userSelectedDate = dateString;
                String[] parts = userSelectedDate.split("-");
                String yearEndDate = parts[1]+"-"+parts[2];
                System.out.println("yearEndDate: "+yearEndDate);
                Boolean isDateCutoffYearEnd = false;
                Boolean isPrevMonthDateCutoffYearEnd = false;
                String prevDayDate = null;
                String prevMonthPrevDayDate = null;
                
                /*if(yearEndDate.equalsIgnoreCase("12-31")){
                    System.out.println("YEAR END CUT OFF SELECTED");
                    isDateCutoffYearEnd = true;
                    //============== GET PREV DAY ===========
                        cal.setTime(jCalReportCutOff.getDate()); 
                        cal.add(Calendar.DAY_OF_MONTH, -1);
                        prevDayDate = SDF.format(cal.getTime());
                        System.out.println("prevDayDate: "+prevDayDate);
                    //=========================================
                }*/
                //============== GET PREV DAY OF CUT OFF ===========
                cal.setTime(jCalReportCutOff.getDate()); 
                cal.add(Calendar.DAY_OF_MONTH, -1);
                prevDayDate = SDF.format(cal.getTime());
                
                System.out.println("prevDayDate: "+prevDayDate);
                //=========================================
                
               
                //============== GET PREV MONTH ===========
                cal.setTime(jCalReportCutOff.getDate()); 
                cal.add(Calendar.MONTH, -1);
                cal.set(Calendar.DATE,cal.getActualMaximum(Calendar.DAY_OF_MONTH));
                String prevMonthDate = SDF.format(cal.getTime());
                
                String[] prevMonthparts = prevMonthDate.split("-");
                String prevMonthyearEndDate = prevMonthparts[1]+"-"+prevMonthparts[2];
                
                //============== GET PREV DAY OF PREVIOUS MONTH ===========
                    System.out.println("prevMonthparts[2]: "+prevMonthparts[2]);
                    Integer prevMonthDayminus1 = Integer.parseInt(prevMonthparts[2]); // day
                    prevMonthDayminus1 = prevMonthDayminus1 - 1;  
                    prevMonthPrevDayDate = prevMonthparts[0]+"-"+prevMonthparts[1]+"-"+prevMonthDayminus1.toString();
                    System.out.println("prevMonthPrevDayDate: "+prevMonthPrevDayDate);
                //=========================================
                /*if(prevMonthyearEndDate.equalsIgnoreCase("12-31")){
                    System.out.println("PREV MONTH YEAR END CUT OFF SELECTED");
                    isPrevMonthDateCutoffYearEnd = true;
                    //============== GET PREV DAY ===========
                      Integer prevMonthDayminus1 = Integer.parseInt(parts[2]); // day
                      prevMonthDayminus1 = prevMonthDayminus1 - 1;  
                      prevDayDate = prevMonthparts[0]+"-"+prevMonthparts[1]+"-"+prevMonthDayminus1.toString();
                      System.out.println("prevDayDate: "+prevDayDate);
                    //=========================================
                }*/
                
                //=========================================
                
                // ============= GET PREV YEAR =============
                Integer theSplittedYear = Integer.parseInt(parts[0]); // year
                theSplittedYear = theSplittedYear - 1;
                String prevYearParam = theSplittedYear+"-12-31";
                String prevYearPrevDayDate = theSplittedYear+"-12-30";
                
                //==============================================
                System.out.println("Cutoff date : "+dateString);
                System.out.println("prevDayDate: "+prevDayDate);
                
                System.out.println("prevMonthDate: "+prevMonthDate);
                System.out.println("prevMonthPrevDayDate: "+prevMonthPrevDayDate);
                
                System.out.println("prevYearParam: "+prevYearParam);
                 System.out.println("prevYearPrevDayDate: "+prevYearPrevDayDate);
                
                String rep_code = "FRPWORKFILECOMPFS-CONSO";
                String branchId="";
                btnGenerate.setEnabled(false);
                String xstarter = "START";
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                String xmenuAction = "COMPARATIVE-CONSO";
                try {

                    //if (chkConsolidateFlag.isSelected() == true){
                        if(xstarter.equalsIgnoreCase("START")){
                            // ============= MAY IF DATI ======================
                            //start

                            String sqlstr = "";
                            Connection conn = ConnectionManager.getConnection();
                            Statement st = conn.createStatement();
                            String excelTemplate = CreateReport.getReportTemplate("FRPWORKFILECOMPFS-CONSO");
                            Integer xrow = 1;
                            Integer xcol = 1;
                            String current = new java.io.File( "." ).getCanonicalPath();
                            XSSFWorkbook report_excel_template; // for xlsx/xlsm
                            // convert it into a POI object
                            //Read Excel document first

                            FileInputStream input_document = new FileInputStream(new File(current+excelTemplate));
                            // convert it into a POI object
                            report_excel_template = new XSSFWorkbook(input_document);
                            //

                            // ========================= COMPARATIVE CONSO CUT OFF DATE REPORT GENERATION SECTION ========================
                            ResultSet rs2 = null;
                            System.out.println("isDateCutoffYearEnd: "+isDateCutoffYearEnd);
                            System.out.println("prevDayDate: "+prevDayDate);
                            System.out.println("dateString: "+dateString);

                            if (xmenuAction.equalsIgnoreCase("COMPARATIVE-CONSO")){
                                System.out.println("==== > COMPARATIVE CONSOLIDATED FINANCIAL STATEMENT GENERATION");
                                //GET FS CUT OFF DATE QUERY
                                sqlstr = CreateReport.getReportQueryFSConso(dateString,prevDayDate);
                                rs2 = st.executeQuery(sqlstr);
                            }
                            if(!rs2.isBeforeFirst()){
                                System.out.println("NO VALUE");
                                XSSFSheet report_worksheet;
                                report_worksheet = report_excel_template.getSheet("ICBS-TB-GL-CutOff-Date");
                                System.out.println("row value" + report_worksheet.getLastRowNum());

                                for (int x =1; x <=  report_worksheet.getLastRowNum(); x++){
                                    Row row = report_worksheet.getRow(x);
                                    for(int y=1;y<6;y++){
                                        System.out.println("row : " + x + "col :" + y);
                                        System.out.println("CELL CLEANING TB GL");
                                        Cell cell = row.getCell(y);
                                        if (cell == null){
                                            cell = row.createCell(y);
                                        }
                                        cell.setCellValue(" ");

                                    }
                                }
                            }else{
                                System.out.println("WITH DATA VALUE");
                                while (rs2.next()){
                                    System.out.println("ROW GL" + xrow);
                                    System.out.println("Column 1 " + rs2.getString(1));
                                    System.out.println("Column 2 " + rs2.getString(2));
                                    System.out.println("Column 3 " + rs2.getString(3));
                                    System.out.println("Column 4 " + rs2.getString(4));
                                    System.out.println("Column 5 " + rs2.getString(5));
                                    XSSFSheet report_worksheet;
                                    report_worksheet = report_excel_template.getSheet("ICBS-TB-GL-CutOff-Date");
                                    // System.out.println("row value" + report_worksheet.getLastRowNum());

                                    Row row = report_worksheet.getRow(xrow);

                                    //create new row if row is null
                                    if (row == null) {
                                        // No entries in this row
                                        // Handle empty
                                        // continue;
                                        row = report_worksheet.createRow(xrow);
                                    }

                                    for(int y=1;y<6;y++){
                                        System.out.println("row : " + xrow + "col :" + y);
                                        System.out.println("CELL CLEANING");
                                        System.out.println("rs2.getString(y): "+rs2.getString(y));
                                        String getValue;

                                        Cell cell = row.getCell(y);
                                        if (cell == null){
                                            cell = row.createCell(y);
                                        }
                                        if(y < 4){
                                            if(isNullOrBlank(rs2.getString(y))){
                                                cell.setCellValue(" ");
                                            }else{
                                                cell.setCellValue(rs2.getString(y));
                                            }

                                        }else{
                                            if(isNullOrBlank(rs2.getString(y))){
                                                cell.setCellValue(0.00D);
                                            }else{
                                                cell.setCellValue(Double.parseDouble(rs2.getString(y)));
                                            }
                                            System.out.println("LAST VALUE" + y);
                                        }
                                    } //for loop end

                                    xrow += 1;

                                } // while loop end
                            } // else end
                            
                            // ======================== EXIT COMPARATIVE CONSO CUT OFF DATE REPORT GENERATION SECTION ========================
                            
                            // ======================== START COMPARATIVE CONSO PREVIOUS MONTH DATE REPORT GENERATION SECTION ========================
                            count++;
                            J.setValue(count);
                            Thread.sleep(500);
                            System.out.println("FIRST REPORT END");

                            st.close();
                            xrow = 1;
                            
                            
                            Statement st2 = conn.createStatement();
                            ResultSet rs3 = null;
                            System.out.println("isDateCutoffYearEnd: "+isDateCutoffYearEnd);
                            System.out.println("prevMonthDate: "+prevMonthDate);
                            System.out.println("prevMonthPrevDayDate: "+prevMonthPrevDayDate);

                            if (xmenuAction.equalsIgnoreCase("COMPARATIVE-CONSO")){
                                System.out.println("==== > COMPARATIVE CONSOLIDATED PREV MONTH FINANCIAL STATEMENT GENERATION");
                                //GET FS PREV MONTH DATE QUERY
                                String sqlstr22 = "";

                                sqlstr22 = CreateReport.getReportQueryFSConsoPrevMonth(prevMonthDate,prevMonthPrevDayDate);
                                rs3 = st2.executeQuery(sqlstr22);
                            }
                            if(!rs3.isBeforeFirst()){
                                System.out.println("NO VALUE");
                                XSSFSheet report_worksheet;
                                report_worksheet = report_excel_template.getSheet("ICBS-TB-GL-Prev-Month");
                                System.out.println("row value" + report_worksheet.getLastRowNum());

                                for (int x =1; x <=  report_worksheet.getLastRowNum(); x++){
                                    Row row = report_worksheet.getRow(x);
                                    for(int y=1;y<6;y++){
                                        System.out.println("row : " + x + "col :" + y);
                                        System.out.println("CELL CLEANING TB GL");
                                        Cell cell = row.getCell(y);
                                        if (cell == null){
                                            cell = row.createCell(y);
                                        }
                                        cell.setCellValue(" ");

                                    }
                                }
                            }else{
                                System.out.println("WITH DATA VALUE");
                                while (rs3.next()){
                                    System.out.println("ROW GL" + xrow);
                                    System.out.println("Column 1 " + rs3.getString(1));
                                    System.out.println("Column 2 " + rs3.getString(2));
                                    System.out.println("Column 3 " + rs3.getString(3));
                                    System.out.println("Column 4 " + rs3.getString(4));
                                    System.out.println("Column 5 " + rs3.getString(5));
                                    XSSFSheet report_worksheet;
                                    report_worksheet = report_excel_template.getSheet("ICBS-TB-GL-Prev-Month");
                                    // System.out.println("row value" + report_worksheet.getLastRowNum());

                                    Row row = report_worksheet.getRow(xrow);

                                    //create new row if row is null
                                    if (row == null) {
                                        // No entries in this row
                                        // Handle empty
                                        // continue;
                                        row = report_worksheet.createRow(xrow);
                                    }

                                    for(int y=1;y<6;y++){
                                        System.out.println("row : " + xrow + "col :" + y);
                                        System.out.println("CELL CLEANING");
                                        System.out.println("rs2.getString(y): "+rs3.getString(y));
                                        String getValue;

                                        Cell cell = row.getCell(y);
                                        if (cell == null){
                                            cell = row.createCell(y);
                                        }
                                        if(y < 4){
                                            if(isNullOrBlank(rs3.getString(y))){
                                                cell.setCellValue(" ");
                                            }else{
                                                cell.setCellValue(rs3.getString(y));
                                            }

                                        }else{
                                            if(isNullOrBlank(rs3.getString(y))){
                                                cell.setCellValue(0.00D);
                                            }else{
                                                cell.setCellValue(Double.parseDouble(rs3.getString(y)));
                                            }
                                            System.out.println("LAST VALUE" + y);
                                        }
                                    } //for loop end

                                    xrow += 1;

                                } // while loop end
                            } // else end
                            // ======================== EXIT COMPARATIVE CONSO PREVIOUS MONTH DATE REPORT GENERATION SECTION ========================
                            count++;
                            J.setValue(count);
                            Thread.sleep(500);
                            System.out.println("FIRST REPORT END");

                            st2.close();
                            xrow = 1;
                            
                            Statement st3 = conn.createStatement();
                            ResultSet rs4 = null;
                            System.out.println("isDateCutoffYearEnd: "+isDateCutoffYearEnd);
                            System.out.println("prevYearParam: "+prevYearParam);
                            System.out.println("prevYearPrevDayDate: "+prevYearPrevDayDate);

                            if (xmenuAction.equalsIgnoreCase("COMPARATIVE-CONSO")){
                                System.out.println("==== > COMPARATIVE CONSOLIDATED PREV YEAR FINANCIAL STATEMENT GENERATION");
                                //GET FS PREV MONTH DATE QUERY
                                String sqlstr3 = "";

                                sqlstr3 = CreateReport.getReportQueryFSConsoPrevYear(prevYearParam,prevYearPrevDayDate);
                                rs4 = st3.executeQuery(sqlstr3);
                            }
                            if(!rs4.isBeforeFirst()){
                                System.out.println("NO VALUE");
                                XSSFSheet report_worksheet;
                                report_worksheet = report_excel_template.getSheet("ICBS-TB-GL-Prev-Year");
                                System.out.println("row value" + report_worksheet.getLastRowNum());

                                for (int x =1; x <=  report_worksheet.getLastRowNum(); x++){
                                    Row row = report_worksheet.getRow(x);
                                    for(int y=1;y<6;y++){
                                        System.out.println("row : " + x + "col :" + y);
                                        System.out.println("CELL CLEANING TB GL");
                                        Cell cell = row.getCell(y);
                                        if (cell == null){
                                            cell = row.createCell(y);
                                        }
                                        cell.setCellValue(" ");

                                    }
                                }
                            }else{
                                System.out.println("WITH DATA VALUE");
                                while (rs4.next()){
                                    System.out.println("ROW GL" + xrow);
                                    System.out.println("Column 1 " + rs4.getString(1));
                                    System.out.println("Column 2 " + rs4.getString(2));
                                    System.out.println("Column 3 " + rs4.getString(3));
                                    System.out.println("Column 4 " + rs4.getString(4));
                                    System.out.println("Column 5 " + rs4.getString(5));
                                    XSSFSheet report_worksheet;
                                    report_worksheet = report_excel_template.getSheet("ICBS-TB-GL-Prev-Year");
                                    // System.out.println("row value" + report_worksheet.getLastRowNum());

                                    Row row = report_worksheet.getRow(xrow);

                                    //create new row if row is null
                                    if (row == null) {
                                        // No entries in this row
                                        // Handle empty
                                        // continue;
                                        row = report_worksheet.createRow(xrow);
                                    }

                                    for(int y=1;y<6;y++){
                                        System.out.println("row : " + xrow + "col :" + y);
                                        System.out.println("CELL CLEANING");
                                        System.out.println("rs2.getString(y): "+rs4.getString(y));
                                        String getValue;

                                        Cell cell = row.getCell(y);
                                        if (cell == null){
                                            cell = row.createCell(y);
                                        }
                                        if(y < 4){
                                            if(isNullOrBlank(rs4.getString(y))){
                                                cell.setCellValue(" ");
                                            }else{
                                                cell.setCellValue(rs4.getString(y));
                                            }

                                        }else{
                                            if(isNullOrBlank(rs4.getString(y))){
                                                cell.setCellValue(0.00D);
                                            }else{
                                                cell.setCellValue(Double.parseDouble(rs4.getString(y)));
                                            }
                                            System.out.println("LAST VALUE" + y);
                                        }
                                    } //for loop end

                                    xrow += 1;

                                } // while loop end
                            } // else end
                            // ======================== EXIT COMPARATIVE CONSO PREVIOUS MONTH DATE REPORT GENERATION SECTION ========================
                            count++;
                            J.setValue(count);
                            Thread.sleep(500);
                            System.out.println("FIRST REPORT END");

                            st3.close();
                            xrow = 1;
                            System.out.println("====== DONE WRITTING TO FS EXCEL WORKFILE ============");
                            count++;
                            J.setValue(count);
                            Thread.sleep(500);
                            //Overwrite excell
                            //XSSFFormulaEvaluator.evaluateAllFormulaCells(report_excel_template);
                           
                            System.out.println("Evaluating foumulas");
                            //FormulaEvaluator xevaluator = report_excel_template.getCreationHelper().createFormulaEvaluator();
                            //xevaluator.setIgnoreMissingWorkbooks(true);
                            //System.out.println("FORMULA" + xevaluator);
                            /*for (Sheet sheet : report_excel_template){
                                System.out.println("Sheet" + sheet);
                                for(Row r : sheet){
                                    for(Cell c: r ){

                                        if(c.getCellType() == Cell.CELL_TYPE_FORMULA){
                                            xevaluator.evaluateFormulaCell(c);

                                        }
                                    }
                                }
                            }*/
                            
                            System.out.println ("current+excelTemplate " + current+excelTemplate);
                            FileOutputStream output_file =new FileOutputStream(new File(current+excelTemplate));
                            count++;
                            J.setValue(count);

                            //write changes
                            report_excel_template.write(output_file);
                            //close the stream
                            output_file.close();
                            //START
                            //end
                            J.setMaximum(2);
                        }
                        count++;
                        J.setValue(count);
                        btnGenerate.setEnabled(true);
                        setCursor(null);
                        JOptionPane.showMessageDialog(rootPane, "Report Complete!");
                        jCalReportCutOff.setDate(new Date());
                        jCalReportCutOff.setNullAllowed(true);
                        J.setValue(0);
                        //            //END FS
                    } catch (SQLException ex) {
                        Logger.getLogger(FSReportJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(FSReportJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InterruptedException e)
                    {

                    }
                }
            });
            thread.start();
    }//GEN-LAST:event_btnGenerateActionPerformed
    private static boolean isNullOrBlank(String s){
        return (s==null || s.trim().equals(""));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JProgressBar J;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerate;
    private org.freixas.jcalendar.JCalendarCombo jCalReportCutOff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
