/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expresso_report_package;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import expresso_report_package.MainJFrame;
import expresso_report_package.SettingJInternalFrame;

/**
 *
 * @author Jasmine
 */
public class LoginJInternalFrame extends javax.swing.JInternalFrame {
    /**
     * Creates new form LoginJInternalFrame
     */
    int count = 3;
            
    public LoginJInternalFrame() {
        initComponents();
        
        Connection conn = null;
        try {
            conn = ConnectionManager.getConnection();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(LoginJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {      
            Statement st = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(LoginJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBox_UserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(88, 33));
        setPreferredSize(new java.awt.Dimension(410, 322));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Password:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPasswordField1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtBox_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBox_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validate_login(String username,String password){
         try {
            Connection conn = ConnectionManager.getConnection();
            //String query = "select username,password from user_master where username= '"+username+"' and password= '"+password+"'";
            
            PreparedStatement pst = conn.prepareStatement("select username,password from user_master where username=? and password=?");
            pst.setString(1, username);
            pst.setString(2, password);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                return true;
            }                         
        } catch (SQLException | IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(AmlcJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
      
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          
            String user = txtBox_UserName.getText();
            char[] password = jPasswordField1.getPassword();
            String pass = String.valueOf(password);
            String original = pass;
            MessageDigest md;
            String newHashPasword = "";    
            try {
                md = MessageDigest.getInstance("MD5");
                md.update(original.getBytes());
		byte[] digest = md.digest();
		StringBuffer sb = new StringBuffer();
		for (byte b : digest) {
			sb.append(String.format("%02x", b & 0xff));
		}
                newHashPasword = sb.toString();
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(LoginJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("hash password: "+newHashPasword);

            if(count != 0){
               if(validate_login(user,newHashPasword)){
                                   
                JOptionPane.showMessageDialog(null,"Login Successful!");
                txtBox_UserName.setEnabled(false);
                jPasswordField1.setEnabled(false);
                jButton1.setEnabled(false);
                                                                   
               MainJFrame frm = null;
                try {
                    frm = new MainJFrame();
                } catch (IOException | SQLException ex) {
                    Logger.getLogger(LoginJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                frm.setVisible(true);
                frm.jMenuReports.enable();
                frm.jMenuItemConnection.setEnabled(false);
                frm.jMenuItemDataForm.setVisible(true);

             }
            else {
          
                JOptionPane.showMessageDialog(null,"Login Failed!");
                txtBox_UserName.setText("");
                jPasswordField1.setText("");
                txtBox_UserName.requestFocus();
                count--;
               // System.exit(0);
            }    
        }    
        if (count == 0){
            JOptionPane.showMessageDialog(null,"Maximum number of attempts exceeded!");
            System.exit(0); 
            }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtBox_UserName;
    // End of variables declaration//GEN-END:variables
}
